//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Prism
{
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class PrismGeolocalizedInformation : PrismSubareaEmptyInfo
    {
        
        public const int ProtocolId = 434;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private PrismInformation m_prism;
        
        public virtual PrismInformation Prism
        {
            get
            {
                return m_prism;
            }
            set
            {
                m_prism = value;
            }
        }
        
        private short m_worldX;
        
        public virtual short WorldX
        {
            get
            {
                return m_worldX;
            }
            set
            {
                m_worldX = value;
            }
        }
        
        private short m_worldY;
        
        public virtual short WorldY
        {
            get
            {
                return m_worldY;
            }
            set
            {
                m_worldY = value;
            }
        }
        
        private int m_mapId;
        
        public virtual int MapId
        {
            get
            {
                return m_mapId;
            }
            set
            {
                m_mapId = value;
            }
        }
        
        public PrismGeolocalizedInformation(PrismInformation prism, short worldX, short worldY, int mapId)
        {
            m_prism = prism;
            m_worldX = worldX;
            m_worldY = worldY;
            m_mapId = mapId;
        }
        
        public PrismGeolocalizedInformation()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_prism.TypeID)));
            m_prism.Serialize(writer);
            writer.WriteShort(m_worldX);
            writer.WriteShort(m_worldY);
            writer.WriteInt(m_mapId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_prism = ProtocolManager.GetTypeInstance<PrismInformation>(reader.ReadUShort());
            m_prism.Deserialize(reader);
            m_worldX = reader.ReadShort();
            m_worldY = reader.ReadShort();
            m_mapId = reader.ReadInt();
        }
    }
}
