//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class PortalUseRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6492;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_portalId;
        
        public virtual uint PortalId
        {
            get
            {
                return m_portalId;
            }
            set
            {
                m_portalId = value;
            }
        }
        
        public PortalUseRequestMessage(uint portalId)
        {
            m_portalId = portalId;
        }
        
        public PortalUseRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhInt(m_portalId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_portalId = reader.ReadVarUhInt();
        }
    }
}
