//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Context.Fight
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class GameFightMinimalStatsPreparation : GameFightMinimalStats
    {
        
        public const int ProtocolId = 360;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_initiative;
        
        public virtual uint Initiative
        {
            get
            {
                return m_initiative;
            }
            set
            {
                m_initiative = value;
            }
        }
        
        public GameFightMinimalStatsPreparation(uint initiative)
        {
            m_initiative = initiative;
        }
        
        public GameFightMinimalStatsPreparation()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_initiative);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_initiative = reader.ReadVarUhInt();
        }
    }
}
