//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Fight
{
    using DofusBot.Protocol.Network.Types.Game.Context.Fight;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameFightUpdateTeamMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5572;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private FightTeamInformations m_team;
        
        public virtual FightTeamInformations Team
        {
            get
            {
                return m_team;
            }
            set
            {
                m_team = value;
            }
        }
        
        private short m_fightId;
        
        public virtual short FightId
        {
            get
            {
                return m_fightId;
            }
            set
            {
                m_fightId = value;
            }
        }
        
        public GameFightUpdateTeamMessage(FightTeamInformations team, short fightId)
        {
            m_team = team;
            m_fightId = fightId;
        }
        
        public GameFightUpdateTeamMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_team.Serialize(writer);
            writer.WriteShort(m_fightId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_team = new FightTeamInformations();
            m_team.Deserialize(reader);
            m_fightId = reader.ReadShort();
        }
    }
}
