//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Friend
{
    using DofusBot.Protocol.Network.Types.Game.Friend;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class FriendUpdateMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5924;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private FriendInformations m_friendUpdated;
        
        public virtual FriendInformations FriendUpdated
        {
            get
            {
                return m_friendUpdated;
            }
            set
            {
                m_friendUpdated = value;
            }
        }
        
        public FriendUpdateMessage(FriendInformations friendUpdated)
        {
            m_friendUpdated = friendUpdated;
        }
        
        public FriendUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_friendUpdated.TypeID)));
            m_friendUpdated.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_friendUpdated = ProtocolManager.GetTypeInstance<FriendInformations>(reader.ReadUShort());
            m_friendUpdated.Deserialize(reader);
        }
    }
}
