//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Friend
{
    using DofusBot.Protocol.Network.Types.Game.Friend;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class FriendAddedMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5599;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private FriendInformations m_friendAdded;
        
        public virtual FriendInformations FriendAdded
        {
            get
            {
                return m_friendAdded;
            }
            set
            {
                m_friendAdded = value;
            }
        }
        
        public FriendAddedMessage(FriendInformations friendAdded)
        {
            m_friendAdded = friendAdded;
        }
        
        public FriendAddedMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_friendAdded.TypeID)));
            m_friendAdded.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_friendAdded = ProtocolManager.GetTypeInstance<FriendInformations>(reader.ReadUShort());
            m_friendAdded.Deserialize(reader);
        }
    }
}
