//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Context.Fight
{
    using DofusBot.Protocol.Network.Types.Game.Look;
    using DofusBot.Protocol.Network.Types.Game.Context;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class GameFightMonsterInformations : GameFightAIInformations
    {
        
        public const int ProtocolId = 29;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_creatureGenericId;
        
        public virtual ushort CreatureGenericId
        {
            get
            {
                return m_creatureGenericId;
            }
            set
            {
                m_creatureGenericId = value;
            }
        }
        
        private byte m_creatureGrade;
        
        public virtual byte CreatureGrade
        {
            get
            {
                return m_creatureGrade;
            }
            set
            {
                m_creatureGrade = value;
            }
        }
        
        public GameFightMonsterInformations(ushort creatureGenericId, byte creatureGrade)
        {
            m_creatureGenericId = creatureGenericId;
            m_creatureGrade = creatureGrade;
        }
        
        public GameFightMonsterInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_creatureGenericId);
            writer.WriteByte(m_creatureGrade);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_creatureGenericId = reader.ReadVarUhShort();
            m_creatureGrade = reader.ReadByte();
        }
    }
}
