//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Context.Roleplay
{
    using DofusBot.Protocol.Network.Types.Game.Prism;
    using DofusBot.Protocol.Network.Types.Game.Look;
    using DofusBot.Protocol.Network.Types.Game.Context;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class GameRolePlayPrismInformations : GameRolePlayActorInformations
    {
        
        public const int ProtocolId = 161;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private PrismInformation m_prism;
        
        public virtual PrismInformation Prism
        {
            get
            {
                return m_prism;
            }
            set
            {
                m_prism = value;
            }
        }
        
        public GameRolePlayPrismInformations(PrismInformation prism)
        {
            m_prism = prism;
        }
        
        public GameRolePlayPrismInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_prism.TypeID)));
            m_prism.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_prism = ProtocolManager.GetTypeInstance<PrismInformation>(reader.ReadUShort());
            m_prism.Deserialize(reader);
        }
    }
}
