//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Friend
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class SpouseStatusMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6265;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_hasSpouse;
        
        public virtual bool HasSpouse
        {
            get
            {
                return m_hasSpouse;
            }
            set
            {
                m_hasSpouse = value;
            }
        }
        
        public SpouseStatusMessage(bool hasSpouse)
        {
            m_hasSpouse = hasSpouse;
        }
        
        public SpouseStatusMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_hasSpouse);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_hasSpouse = reader.ReadBoolean();
        }
    }
}
