//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Prism
{
    using DofusBot.Protocol.Network.Types.Game.Character;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class PrismFightAttackerAddMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5893;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private CharacterMinimalPlusLookInformations m_attacker;
        
        public virtual CharacterMinimalPlusLookInformations Attacker
        {
            get
            {
                return m_attacker;
            }
            set
            {
                m_attacker = value;
            }
        }
        
        private ushort m_subAreaId;
        
        public virtual ushort SubAreaId
        {
            get
            {
                return m_subAreaId;
            }
            set
            {
                m_subAreaId = value;
            }
        }
        
        private ushort m_fightId;
        
        public virtual ushort FightId
        {
            get
            {
                return m_fightId;
            }
            set
            {
                m_fightId = value;
            }
        }
        
        public PrismFightAttackerAddMessage(CharacterMinimalPlusLookInformations attacker, ushort subAreaId, ushort fightId)
        {
            m_attacker = attacker;
            m_subAreaId = subAreaId;
            m_fightId = fightId;
        }
        
        public PrismFightAttackerAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_attacker.TypeID)));
            m_attacker.Serialize(writer);
            writer.WriteVarUhShort(m_subAreaId);
            writer.WriteVarUhShort(m_fightId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_attacker = ProtocolManager.GetTypeInstance<CharacterMinimalPlusLookInformations>(reader.ReadUShort());
            m_attacker.Deserialize(reader);
            m_subAreaId = reader.ReadVarUhShort();
            m_fightId = reader.ReadVarUhShort();
        }
    }
}
