//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Context.Roleplay
{
    using DofusBot.Protocol.Network.Types.Game.Look;
    using DofusBot.Protocol.Network.Types.Game.Context;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class GameRolePlayHumanoidInformations : GameRolePlayNamedActorInformations
    {
        
        public const int ProtocolId = 159;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private HumanInformations m_humanoidInfo;
        
        public virtual HumanInformations HumanoidInfo
        {
            get
            {
                return m_humanoidInfo;
            }
            set
            {
                m_humanoidInfo = value;
            }
        }
        
        private int m_accountId;
        
        public virtual int AccountId
        {
            get
            {
                return m_accountId;
            }
            set
            {
                m_accountId = value;
            }
        }
        
        public GameRolePlayHumanoidInformations(HumanInformations humanoidInfo, int accountId)
        {
            m_humanoidInfo = humanoidInfo;
            m_accountId = accountId;
        }
        
        public GameRolePlayHumanoidInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_humanoidInfo.TypeID)));
            m_humanoidInfo.Serialize(writer);
            writer.WriteInt(m_accountId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_humanoidInfo = ProtocolManager.GetTypeInstance<HumanInformations>(reader.ReadUShort());
            m_humanoidInfo.Deserialize(reader);
            m_accountId = reader.ReadInt();
        }
    }
}
