//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Document
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class DocumentReadingBeginMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5675;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_documentId;
        
        public virtual ushort DocumentId
        {
            get
            {
                return m_documentId;
            }
            set
            {
                m_documentId = value;
            }
        }
        
        public DocumentReadingBeginMessage(ushort documentId)
        {
            m_documentId = documentId;
        }
        
        public DocumentReadingBeginMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_documentId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_documentId = reader.ReadVarUhShort();
        }
    }
}
