//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Fight.Character
{
    using DofusBot.Protocol.Network.Types.Game.Context.Fight;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameFightShowFighterMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5864;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private GameFightFighterInformations m_informations;
        
        public virtual GameFightFighterInformations Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public GameFightShowFighterMessage(GameFightFighterInformations informations)
        {
            m_informations = informations;
        }
        
        public GameFightShowFighterMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_informations.TypeID)));
            m_informations.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_informations = ProtocolManager.GetTypeInstance<GameFightFighterInformations>(reader.ReadUShort());
            m_informations.Deserialize(reader);
        }
    }
}
