//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using DofusBot.Protocol.Network.Types.Game.Context.Roleplay.Party;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class PartyUpdateMessage : AbstractPartyEventMessage
    {
        
        public const int ProtocolId = 5575;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private PartyMemberInformations m_memberInformations;
        
        public virtual PartyMemberInformations MemberInformations
        {
            get
            {
                return m_memberInformations;
            }
            set
            {
                m_memberInformations = value;
            }
        }
        
        public PartyUpdateMessage(PartyMemberInformations memberInformations)
        {
            m_memberInformations = memberInformations;
        }
        
        public PartyUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_memberInformations.TypeID)));
            m_memberInformations.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_memberInformations = ProtocolManager.GetTypeInstance<PartyMemberInformations>(reader.ReadUShort());
            m_memberInformations.Deserialize(reader);
        }
    }
}
