//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Character.Stats
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class LifePointsRegenEndMessage : UpdateLifePointsMessage
    {
        
        public const int ProtocolId = 5686;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_lifePointsGained;
        
        public virtual uint LifePointsGained
        {
            get
            {
                return m_lifePointsGained;
            }
            set
            {
                m_lifePointsGained = value;
            }
        }
        
        public LifePointsRegenEndMessage(uint lifePointsGained)
        {
            m_lifePointsGained = lifePointsGained;
        }
        
        public LifePointsRegenEndMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_lifePointsGained);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_lifePointsGained = reader.ReadVarUhInt();
        }
    }
}
