//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Context.Roleplay.Job
{
    using DofusBot.Protocol.Network.Types.Game.Interactive.Skill;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class JobDescription : NetworkType
    {
        
        public const int ProtocolId = 101;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<SkillActionDescription> m_skills;
        
        public virtual List<SkillActionDescription> Skills
        {
            get
            {
                return m_skills;
            }
            set
            {
                m_skills = value;
            }
        }
        
        private byte m_jobId;
        
        public virtual byte JobId
        {
            get
            {
                return m_jobId;
            }
            set
            {
                m_jobId = value;
            }
        }
        
        public JobDescription(List<SkillActionDescription> skills, byte jobId)
        {
            m_skills = skills;
            m_jobId = jobId;
        }
        
        public JobDescription()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort(((short)(m_skills.Count)));
            int skillsIndex;
            for (skillsIndex = 0; (skillsIndex < m_skills.Count); skillsIndex = (skillsIndex + 1))
            {
                SkillActionDescription objectToSend = m_skills[skillsIndex];
                writer.WriteUShort(((ushort)(objectToSend.TypeID)));
                objectToSend.Serialize(writer);
            }
            writer.WriteByte(m_jobId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            int skillsCount = reader.ReadUShort();
            int skillsIndex;
            m_skills = new System.Collections.Generic.List<SkillActionDescription>();
            for (skillsIndex = 0; (skillsIndex < skillsCount); skillsIndex = (skillsIndex + 1))
            {
                SkillActionDescription objectToAdd = ProtocolManager.GetTypeInstance<SkillActionDescription>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_skills.Add(objectToAdd);
            }
            m_jobId = reader.ReadByte();
        }
    }
}
