//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Document
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ComicReadingBeginMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6536;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_comicId;
        
        public virtual ushort ComicId
        {
            get
            {
                return m_comicId;
            }
            set
            {
                m_comicId = value;
            }
        }
        
        public ComicReadingBeginMessage(ushort comicId)
        {
            m_comicId = comicId;
        }
        
        public ComicReadingBeginMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_comicId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_comicId = reader.ReadVarUhShort();
        }
    }
}
