//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Data.Items.Effects
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class ObjectEffectLadder : ObjectEffectCreature
    {
        
        public const int ProtocolId = 81;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_monsterCount;
        
        public virtual uint MonsterCount
        {
            get
            {
                return m_monsterCount;
            }
            set
            {
                m_monsterCount = value;
            }
        }
        
        public ObjectEffectLadder(uint monsterCount)
        {
            m_monsterCount = monsterCount;
        }
        
        public ObjectEffectLadder()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_monsterCount);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_monsterCount = reader.ReadVarUhInt();
        }
    }
}
