//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Actions.Fight
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameActionFightCloseCombatMessage : AbstractGameActionFightTargetedAbilityMessage
    {
        
        public const int ProtocolId = 6116;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_weaponGenericId;
        
        public virtual ushort WeaponGenericId
        {
            get
            {
                return m_weaponGenericId;
            }
            set
            {
                m_weaponGenericId = value;
            }
        }
        
        public GameActionFightCloseCombatMessage(ushort weaponGenericId)
        {
            m_weaponGenericId = weaponGenericId;
        }
        
        public GameActionFightCloseCombatMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_weaponGenericId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_weaponGenericId = reader.ReadVarUhShort();
        }
    }
}
