//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Actions.Fight
{
    using DofusBot.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameActionFightInvisibleObstacleMessage : AbstractGameActionMessage
    {
        
        public const int ProtocolId = 5820;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_sourceSpellId;
        
        public virtual uint SourceSpellId
        {
            get
            {
                return m_sourceSpellId;
            }
            set
            {
                m_sourceSpellId = value;
            }
        }
        
        public GameActionFightInvisibleObstacleMessage(uint sourceSpellId)
        {
            m_sourceSpellId = sourceSpellId;
        }
        
        public GameActionFightInvisibleObstacleMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_sourceSpellId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_sourceSpellId = reader.ReadVarUhInt();
        }
    }
}
