//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Actions.Fight
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameActionFightNoSpellCastMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6132;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_spellLevelId;
        
        public virtual uint SpellLevelId
        {
            get
            {
                return m_spellLevelId;
            }
            set
            {
                m_spellLevelId = value;
            }
        }
        
        public GameActionFightNoSpellCastMessage(uint spellLevelId)
        {
            m_spellLevelId = spellLevelId;
        }
        
        public GameActionFightNoSpellCastMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhInt(m_spellLevelId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_spellLevelId = reader.ReadVarUhInt();
        }
    }
}
