//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Actions.Fight
{
    using DofusBot.Protocol.Network.Messages.Game.Actions;
    using DofusBot.Protocol.Network.Types.Game.Actions.Fight;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameActionFightDispellableEffectMessage : AbstractGameActionMessage
    {
        
        public const int ProtocolId = 6070;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private AbstractFightDispellableEffect m_effect;
        
        public virtual AbstractFightDispellableEffect Effect
        {
            get
            {
                return m_effect;
            }
            set
            {
                m_effect = value;
            }
        }
        
        public GameActionFightDispellableEffectMessage(AbstractFightDispellableEffect effect)
        {
            m_effect = effect;
        }
        
        public GameActionFightDispellableEffectMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_effect.TypeID)));
            m_effect.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_effect = ProtocolManager.GetTypeInstance<AbstractFightDispellableEffect>(reader.ReadUShort());
            m_effect.Deserialize(reader);
        }
    }
}
