//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class TreasureHuntLegendaryRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6499;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_legendaryId;
        
        public virtual ushort LegendaryId
        {
            get
            {
                return m_legendaryId;
            }
            set
            {
                m_legendaryId = value;
            }
        }
        
        public TreasureHuntLegendaryRequestMessage(ushort legendaryId)
        {
            m_legendaryId = legendaryId;
        }
        
        public TreasureHuntLegendaryRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_legendaryId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_legendaryId = reader.ReadVarUhShort();
        }
    }
}
