//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Job
{
    using DofusBot.Protocol.Network.Types.Game.Context.Roleplay.Job;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class JobCrafterDirectoryAddMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5651;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private JobCrafterDirectoryListEntry m_listEntry;
        
        public virtual JobCrafterDirectoryListEntry ListEntry
        {
            get
            {
                return m_listEntry;
            }
            set
            {
                m_listEntry = value;
            }
        }
        
        public JobCrafterDirectoryAddMessage(JobCrafterDirectoryListEntry listEntry)
        {
            m_listEntry = listEntry;
        }
        
        public JobCrafterDirectoryAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_listEntry.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_listEntry = new JobCrafterDirectoryListEntry();
            m_listEntry.Deserialize(reader);
        }
    }
}
