//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Job
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class JobMultiCraftAvailableSkillsMessage : JobAllowMultiCraftRequestMessage
    {
        
        public const int ProtocolId = 5747;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<System.UInt16> m_skills;
        
        public virtual List<System.UInt16> Skills
        {
            get
            {
                return m_skills;
            }
            set
            {
                m_skills = value;
            }
        }
        
        private ulong m_playerId;
        
        public virtual ulong PlayerId
        {
            get
            {
                return m_playerId;
            }
            set
            {
                m_playerId = value;
            }
        }
        
        public JobMultiCraftAvailableSkillsMessage(List<System.UInt16> skills, ulong playerId)
        {
            m_skills = skills;
            m_playerId = playerId;
        }
        
        public JobMultiCraftAvailableSkillsMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(((short)(m_skills.Count)));
            int skillsIndex;
            for (skillsIndex = 0; (skillsIndex < m_skills.Count); skillsIndex = (skillsIndex + 1))
            {
                writer.WriteVarUhShort(m_skills[skillsIndex]);
            }
            writer.WriteVarUhLong(m_playerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            int skillsCount = reader.ReadUShort();
            int skillsIndex;
            m_skills = new System.Collections.Generic.List<ushort>();
            for (skillsIndex = 0; (skillsIndex < skillsCount); skillsIndex = (skillsIndex + 1))
            {
                m_skills.Add(reader.ReadVarUhShort());
            }
            m_playerId = reader.ReadVarUhLong();
        }
    }
}
