//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class PartyInvitationCancelledForGuestMessage : AbstractPartyMessage
    {
        
        public const int ProtocolId = 6256;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_cancelerId;
        
        public virtual ulong CancelerId
        {
            get
            {
                return m_cancelerId;
            }
            set
            {
                m_cancelerId = value;
            }
        }
        
        public PartyInvitationCancelledForGuestMessage(ulong cancelerId)
        {
            m_cancelerId = cancelerId;
        }
        
        public PartyInvitationCancelledForGuestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhLong(m_cancelerId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_cancelerId = reader.ReadVarUhLong();
        }
    }
}
