//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Alliance
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class AllianceKickRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6400;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private uint m_kickedId;
        
        public virtual uint KickedId
        {
            get
            {
                return m_kickedId;
            }
            set
            {
                m_kickedId = value;
            }
        }
        
        public AllianceKickRequestMessage(uint kickedId)
        {
            m_kickedId = kickedId;
        }
        
        public AllianceKickRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhInt(m_kickedId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_kickedId = reader.ReadVarUhInt();
        }
    }
}
