//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Startup
{
    using DofusBot.Protocol.Network.Types.Game.Startup;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class StartupActionAddMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6538;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private StartupActionAddObject m_newAction;
        
        public virtual StartupActionAddObject NewAction
        {
            get
            {
                return m_newAction;
            }
            set
            {
                m_newAction = value;
            }
        }
        
        public StartupActionAddMessage(StartupActionAddObject newAction)
        {
            m_newAction = newAction;
        }
        
        public StartupActionAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_newAction.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_newAction = new StartupActionAddObject();
            m_newAction.Deserialize(reader);
        }
    }
}
