//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Atlas.Compass
{
    using DofusBot.Protocol.Network.Types.Game.Context;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class CompassUpdateMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5591;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private MapCoordinates m_coords;
        
        public virtual MapCoordinates Coords
        {
            get
            {
                return m_coords;
            }
            set
            {
                m_coords = value;
            }
        }
        
        private byte m_type;
        
        public virtual byte Type
        {
            get
            {
                return m_type;
            }
            set
            {
                m_type = value;
            }
        }
        
        public CompassUpdateMessage(MapCoordinates coords, byte type)
        {
            m_coords = coords;
            m_type = type;
        }
        
        public CompassUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_coords.TypeID)));
            m_coords.Serialize(writer);
            writer.WriteByte(m_type);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_coords = ProtocolManager.GetTypeInstance<MapCoordinates>(reader.ReadUShort());
            m_coords.Deserialize(reader);
            m_type = reader.ReadByte();
        }
    }
}
