//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Guild
{
    using DofusBot.Protocol.Network.Types.Game.Guild;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GuildInformationsMemberUpdateMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5597;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private GuildMember m_member;
        
        public virtual GuildMember Member
        {
            get
            {
                return m_member;
            }
            set
            {
                m_member = value;
            }
        }
        
        public GuildInformationsMemberUpdateMessage(GuildMember member)
        {
            m_member = member;
        }
        
        public GuildInformationsMemberUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_member.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_member = new GuildMember();
            m_member.Deserialize(reader);
        }
    }
}
