//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Tinsel
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class OrnamentSelectRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6374;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_ornamentId;
        
        public virtual ushort OrnamentId
        {
            get
            {
                return m_ornamentId;
            }
            set
            {
                m_ornamentId = value;
            }
        }
        
        public OrnamentSelectRequestMessage(ushort ornamentId)
        {
            m_ornamentId = ornamentId;
        }
        
        public OrnamentSelectRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_ornamentId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_ornamentId = reader.ReadVarUhShort();
        }
    }
}
