//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Guild.Tax
{
    using DofusBot.Protocol.Network.Types.Game.Guild.Tax;
    using DofusBot.Protocol.Network;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class TaxCollectorMovementAddMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5917;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private TaxCollectorInformations m_informations;
        
        public virtual TaxCollectorInformations Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public TaxCollectorMovementAddMessage(TaxCollectorInformations informations)
        {
            m_informations = informations;
        }
        
        public TaxCollectorMovementAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_informations.TypeID)));
            m_informations.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_informations = ProtocolManager.GetTypeInstance<TaxCollectorInformations>(reader.ReadUShort());
            m_informations.Deserialize(reader);
        }
    }
}
