//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Guild.Tax
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class TaxCollectorMovementRemoveMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5915;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private int m_collectorId;
        
        public virtual int CollectorId
        {
            get
            {
                return m_collectorId;
            }
            set
            {
                m_collectorId = value;
            }
        }
        
        public TaxCollectorMovementRemoveMessage(int collectorId)
        {
            m_collectorId = collectorId;
        }
        
        public TaxCollectorMovementRemoveMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteInt(m_collectorId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_collectorId = reader.ReadInt();
        }
    }
}
