//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangeCraftResultMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5790;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_craftResult;
        
        public virtual byte CraftResult
        {
            get
            {
                return m_craftResult;
            }
            set
            {
                m_craftResult = value;
            }
        }
        
        public ExchangeCraftResultMessage(byte craftResult)
        {
            m_craftResult = craftResult;
        }
        
        public ExchangeCraftResultMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_craftResult);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_craftResult = reader.ReadByte();
        }
    }
}
