//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangeTypesExchangerDescriptionForUserMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5765;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private List<System.UInt32> m_typeDescription;
        
        public virtual List<System.UInt32> TypeDescription
        {
            get
            {
                return m_typeDescription;
            }
            set
            {
                m_typeDescription = value;
            }
        }
        
        public ExchangeTypesExchangerDescriptionForUserMessage(List<System.UInt32> typeDescription)
        {
            m_typeDescription = typeDescription;
        }
        
        public ExchangeTypesExchangerDescriptionForUserMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteShort(((short)(m_typeDescription.Count)));
            int typeDescriptionIndex;
            for (typeDescriptionIndex = 0; (typeDescriptionIndex < m_typeDescription.Count); typeDescriptionIndex = (typeDescriptionIndex + 1))
            {
                writer.WriteVarUhInt(m_typeDescription[typeDescriptionIndex]);
            }
        }
        
        public override void Deserialize(IDataReader reader)
        {
            int typeDescriptionCount = reader.ReadUShort();
            int typeDescriptionIndex;
            m_typeDescription = new System.Collections.Generic.List<uint>();
            for (typeDescriptionIndex = 0; (typeDescriptionIndex < typeDescriptionCount); typeDescriptionIndex = (typeDescriptionIndex + 1))
            {
                m_typeDescription.Add(reader.ReadVarUhInt());
            }
        }
    }
}
