//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using DofusBot.Protocol.Network.Types.Game.Mount;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangeMountStableAddMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5971;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private MountClientData m_mountDescription;
        
        public virtual MountClientData MountDescription
        {
            get
            {
                return m_mountDescription;
            }
            set
            {
                m_mountDescription = value;
            }
        }
        
        public ExchangeMountStableAddMessage(MountClientData mountDescription)
        {
            m_mountDescription = mountDescription;
        }
        
        public ExchangeMountStableAddMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            m_mountDescription.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_mountDescription = new MountClientData();
            m_mountDescription.Deserialize(reader);
        }
    }
}
