//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Storage
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class StorageKamasUpdateMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5645;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ulong m_kamasTotal;
        
        public virtual ulong KamasTotal
        {
            get
            {
                return m_kamasTotal;
            }
            set
            {
                m_kamasTotal = value;
            }
        }
        
        public StorageKamasUpdateMessage(ulong kamasTotal)
        {
            m_kamasTotal = kamasTotal;
        }
        
        public StorageKamasUpdateMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhLong(m_kamasTotal);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_kamasTotal = reader.ReadVarUhLong();
        }
    }
}
