//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Mount
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class PaddockMoveItemRequestMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6052;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ushort m_oldCellId;
        
        public virtual ushort OldCellId
        {
            get
            {
                return m_oldCellId;
            }
            set
            {
                m_oldCellId = value;
            }
        }
        
        private ushort m_newCellId;
        
        public virtual ushort NewCellId
        {
            get
            {
                return m_newCellId;
            }
            set
            {
                m_newCellId = value;
            }
        }
        
        public PaddockMoveItemRequestMessage(ushort oldCellId, ushort newCellId)
        {
            m_oldCellId = oldCellId;
            m_newCellId = newCellId;
        }
        
        public PaddockMoveItemRequestMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteVarUhShort(m_oldCellId);
            writer.WriteVarUhShort(m_newCellId);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_oldCellId = reader.ReadVarUhShort();
            m_newCellId = reader.ReadVarUhShort();
        }
    }
}
