//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Types.Game.Guild.Tax
{
    using DofusBot.Protocol.Network.Types.Game.Fight;
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    
    
    using DofusBot.Protocol;
    
    
    public class TaxCollectorWaitingForHelpInformations : TaxCollectorComplementaryInformations
    {
        
        public const int ProtocolId = 447;
        
        public override int TypeID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private ProtectedEntityWaitingForHelpInfo m_waitingForHelpInfo;
        
        public virtual ProtectedEntityWaitingForHelpInfo WaitingForHelpInfo
        {
            get
            {
                return m_waitingForHelpInfo;
            }
            set
            {
                m_waitingForHelpInfo = value;
            }
        }
        
        public TaxCollectorWaitingForHelpInformations(ProtectedEntityWaitingForHelpInfo waitingForHelpInfo)
        {
            m_waitingForHelpInfo = waitingForHelpInfo;
        }
        
        public TaxCollectorWaitingForHelpInformations()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            base.Serialize(writer);
            m_waitingForHelpInfo.Serialize(writer);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            base.Deserialize(reader);
            m_waitingForHelpInfo = new ProtectedEntityWaitingForHelpInfo();
            m_waitingForHelpInfo.Deserialize(reader);
        }
    }
}
