//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class GameFightReadyMessage : NetworkMessage
    {
        
        public const int ProtocolId = 708;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_isReady;
        
        public virtual bool IsReady
        {
            get
            {
                return m_isReady;
            }
            set
            {
                m_isReady = value;
            }
        }
        
        public GameFightReadyMessage(bool isReady)
        {
            m_isReady = isReady;
        }
        
        public GameFightReadyMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_isReady);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_isReady = reader.ReadBoolean();
        }
    }
}
