//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangeObjectMessage : NetworkMessage
    {
        
        public const int ProtocolId = 5515;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private bool m_remote;
        
        public virtual bool Remote
        {
            get
            {
                return m_remote;
            }
            set
            {
                m_remote = value;
            }
        }
        
        public ExchangeObjectMessage(bool remote)
        {
            m_remote = remote;
        }
        
        public ExchangeObjectMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteBoolean(m_remote);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_remote = reader.ReadBoolean();
        }
    }
}
