//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DofusBot.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using DofusBot.Protocol.Network.Messages;
    using DofusBot.Protocol.Network.Types;
    using DofusBot.Protocol;
    
    
    public class ExchangeCraftSlotCountIncreasedMessage : NetworkMessage
    {
        
        public const int ProtocolId = 6125;
        
        public override int MessageID
        {
            get
            {
                return ProtocolId;
            }
        }
        
        private byte m_newMaxSlot;
        
        public virtual byte NewMaxSlot
        {
            get
            {
                return m_newMaxSlot;
            }
            set
            {
                m_newMaxSlot = value;
            }
        }
        
        public ExchangeCraftSlotCountIncreasedMessage(byte newMaxSlot)
        {
            m_newMaxSlot = newMaxSlot;
        }
        
        public ExchangeCraftSlotCountIncreasedMessage()
        {
        }
        
        public override void Serialize(IDataWriter writer)
        {
            writer.WriteByte(m_newMaxSlot);
        }
        
        public override void Deserialize(IDataReader reader)
        {
            m_newMaxSlot = reader.ReadByte();
        }
    }
}
